//290621
export const objectsFetch = {
  START_FETCH_OF_OBJS: 'START_FETCH_OF_OBJS',
  SUCCESS_FETCH_OF_OBJS: 'SUCCESS_FETCH_OF_OBJS',
  ERROR_FETCH_OF_OBJS: 'ERROR_FETCH_OF_OBJS',
};

//290621
export const objectsData = {
  SELECTED_OBJECT: 'SELECTED_OBJECT',
  SELECTED_REL_OBJECT: 'SELECTED_REL_OBJECT',
};




