
//270521
export const userFetch = {
  SET_ERROR_AUTH_USER_FOR_CONSENT_PAGE: 'SET_ERROR_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 210521
  SET_ERROR_OBJ_OF_AUTH_USER_FOR_CONSENT_PAGE: 'SET_ERROR_OBJ_OF_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 210521
  GET_AUTH_USER_FOR_CONSENT_PAGE: 'GET_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 210521
  GET_ORG_OF_AUTH_USER_FOR_CONSENT_PAGE: 'GET_ORG_OF_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 210521
  GET_OBJS_OF_AUTH_USER_FOR_CONSENT_PAGE: 'GET_OBJS_OF_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 210521
  EVENTS_OF_OBJS_FOR_AUTH_USER_FOR_CONSENT_PAGE: 'EVENTS_OF_OBJS_FOR_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 280521


};

//270521
export const objsFetch = {
  EVENTS_OF_OBJS_FOR_AUTH_USER_FOR_CONSENT_PAGE: 'EVENTS_OF_OBJS_FOR_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 280521
  LOCAL_DATA_OF_OBJS_FOR_AUTH_USER_FOR_CONSENT_PAGE: 'LOCAL_DATA_OF_OBJS_FOR_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 280521
  DATA_ONE_OBJ_FOR_AUTH_USER_FOR_CONSENT_PAGE_E: 'DATA_ONE_OBJ_FOR_AUTH_USER_FOR_CONSENT_PAGE_E', //   for consent Page 280521
};

//270521
export const objsData = {
  SET_ACTIVE_OBJ_FOR_CONSENT_PAGE: 'SET_ACTIVE_OBJ_FOR_CONSENT_PAGE', //   выделенный объект - выбранный пользователем /consent page 270521
  SET_CUR_OBJ_ID_FOR_CONSENT_PAGE: 'SET_CUR_OBJ_ID_FOR_CONSENT_PAGE', //   выделенный объект - выбранный пользователем /consent page 270521
  UPDATE_SME_OBJS_FOR_CONSENT_PAGE: 'UPDATE_SME_OBJS_FOR_CONSENT_PAGE', //   выделенный объект - выбранный пользователем /consent page 270521
  FETCH_RELATIVES_OBJS_OF_AUTH_USER_FOR_CONSENT_PAGE: 'FETCH_RELATIVES_OBJS_OF_AUTH_USER_FOR_CONSENT_PAGE', //   for consent Page 280521

};

//060621
export const relObjs = {
  FETCH_REL_OBJ_FOR_CONSENT_PAGE: 'FETCH_REL_OBJ_FOR_CONSENT_PAGE',
  SET_ACTIVE_REL_OBJ_FOR_CONSENT_PAGE: 'SET_ACTIVE_REL_OBJ_FOR_CONSENT_PAGE',
};



